name: loxia
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  postgres: ^3.1.1
  sqflite_common: ^2.5.3
  sqflite_common_ffi: ^2.1.1+1
  type_plus: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
