name: loxia_annotations
description: Annotations for the Loxia ORM library.
version: 0.0.1-dev.1
repository: https://github.com/francescovallone/loxia


environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
