name: loxia_generators
description: Set of generators for the Loxia ORM library.
version: 0.0.1-dev.3
repository: https://github.com/francescovallone/loxia

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  loxia_annotations: ^0.0.1-dev.1
  meta: ^1.12.0
  path: ^1.9.0
  source_gen: ^1.5.0
  source_helper: ^1.3.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
