name: loxia
description: Loxia is a Dart ORM library that aims to be fully-featured, easy-to-use, and flexible to manage entities and relations in your server-side applications.
version: 0.0.1-dev.1
repository: https://github.com/francescovallone/loxia

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  postgres: ^3.1.1
  sqflite_common: ^2.5.3
  sqflite_common_ffi: ^2.1.1+1
  loxia_annotations: ^0.0.1-dev.1
  # path: ^1.8.0

dev_dependencies:
  loxia_generators: ^0.0.1-dev.1
  build_runner: ^2.3.3
  lints: ^3.0.0
  test: ^1.24.0
